var Templates = {}; 

Templates["awardsList"] = 
  function anonymous(locals) {
jade.debug = [{ lineno: 1, filename: undefined }];
try {
var buf = [];
var locals_ = (locals || {}),awards = locals_.awards;jade.indent = [];
jade.debug.unshift({ lineno: 1, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 1, filename: jade.debug[0].filename });
buf.push("\n<table cellspacing=\"0\" cellpadding=\"5\" width=\"100%\" style=\"font-size:11px;border-top:1px solid #ccc;border-bottom:1px solid #ccc;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 2, filename: jade.debug[0].filename });
var cellStyle1 = "background-color: #f3f3f3;";
jade.debug.shift();
jade.debug.unshift({ lineno: 3, filename: jade.debug[0].filename });
var cellStyle2 = "background-color: #f8f8f8;";
jade.debug.shift();
jade.debug.unshift({ lineno: 4, filename: jade.debug[0].filename });
var linkStyle = "text-decoration: none; color: #666;";
jade.debug.shift();
jade.debug.unshift({ lineno: 5, filename: jade.debug[0].filename });
var spanStyle = "color: #999;";
jade.debug.shift();
jade.debug.unshift({ lineno: 8, filename: jade.debug[0].filename });
buf.push("\n  <tbody>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 8, filename: jade.debug[0].filename });
// iterate awards
;(function(){
  var $$obj = awards;
  if ('number' == typeof $$obj.length) {

    for (var i = 0, $$l = $$obj.length; i < $$l; i++) {
      var award = $$obj[i];

jade.debug.unshift({ lineno: 8, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 10, filename: jade.debug[0].filename });
buf.push("\n    <tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 10, filename: jade.debug[0].filename });
buf.push("\n      <td" + (jade.attrs({ 'style':(i % 2 == 0 ? cellStyle1 : cellStyle2) }, {"style":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 11, filename: jade.debug[0].filename });
buf.push("<a" + (jade.attrs({ 'href':(award.href), 'style':(linkStyle), 'target':("_blank") }, {"href":true,"style":true,"target":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 12, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 12, filename: jade.debug[0].filename });
buf.push("" + (jade.escape((jade.interp = award.year) == null ? '' : jade.interp)) + " " + (jade.escape((jade.interp = award.position) == null ? '' : jade.interp)) + "");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 13, filename: jade.debug[0].filename });
buf.push("&nbsp;");
jade.debug.shift();
jade.debug.unshift({ lineno: 14, filename: jade.debug[0].filename });
buf.push(jade.escape(null == (jade.interp = award.app) ? "" : jade.interp));
jade.debug.shift();
jade.debug.unshift({ lineno: 15, filename: jade.debug[0].filename });
buf.push("&nbsp;");
jade.debug.shift();
jade.debug.unshift({ lineno: 16, filename: jade.debug[0].filename });
buf.push("<span" + (jade.attrs({ 'style':(spanStyle) }, {"style":true})) + ">" + (jade.escape(null == (jade.interp = award.award) ? "" : jade.interp)));
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.shift();
buf.push("</span>");
jade.debug.shift();
jade.debug.unshift({ lineno: 17, filename: jade.debug[0].filename });
buf.push("&nbsp;");
jade.debug.shift();
jade.debug.unshift({ lineno: 18, filename: jade.debug[0].filename });
buf.push("<strong" + (jade.attrs({ 'style':(spanStyle) }, {"style":true})) + ">" + (jade.escape(null == (jade.interp = award.competition) ? "" : jade.interp)));
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n    </tr>");
jade.debug.shift();
jade.debug.shift();
    }

  } else {
    var $$l = 0;
    for (var i in $$obj) {
      $$l++;      var award = $$obj[i];

jade.debug.unshift({ lineno: 8, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 10, filename: jade.debug[0].filename });
buf.push("\n    <tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 10, filename: jade.debug[0].filename });
buf.push("\n      <td" + (jade.attrs({ 'style':(i % 2 == 0 ? cellStyle1 : cellStyle2) }, {"style":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 11, filename: jade.debug[0].filename });
buf.push("<a" + (jade.attrs({ 'href':(award.href), 'style':(linkStyle), 'target':("_blank") }, {"href":true,"style":true,"target":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 12, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 12, filename: jade.debug[0].filename });
buf.push("" + (jade.escape((jade.interp = award.year) == null ? '' : jade.interp)) + " " + (jade.escape((jade.interp = award.position) == null ? '' : jade.interp)) + "");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 13, filename: jade.debug[0].filename });
buf.push("&nbsp;");
jade.debug.shift();
jade.debug.unshift({ lineno: 14, filename: jade.debug[0].filename });
buf.push(jade.escape(null == (jade.interp = award.app) ? "" : jade.interp));
jade.debug.shift();
jade.debug.unshift({ lineno: 15, filename: jade.debug[0].filename });
buf.push("&nbsp;");
jade.debug.shift();
jade.debug.unshift({ lineno: 16, filename: jade.debug[0].filename });
buf.push("<span" + (jade.attrs({ 'style':(spanStyle) }, {"style":true})) + ">" + (jade.escape(null == (jade.interp = award.award) ? "" : jade.interp)));
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.shift();
buf.push("</span>");
jade.debug.shift();
jade.debug.unshift({ lineno: 17, filename: jade.debug[0].filename });
buf.push("&nbsp;");
jade.debug.shift();
jade.debug.unshift({ lineno: 18, filename: jade.debug[0].filename });
buf.push("<strong" + (jade.attrs({ 'style':(spanStyle) }, {"style":true})) + ">" + (jade.escape(null == (jade.interp = award.competition) ? "" : jade.interp)));
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n    </tr>");
jade.debug.shift();
jade.debug.shift();
    }

  }
}).call(this);

jade.debug.shift();
jade.debug.shift();
buf.push("\n  </tbody>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n</table>");
jade.debug.shift();
jade.debug.shift();;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade.debug[0].filename, jade.debug[0].lineno);
}
};

Templates["awardsSimple"] = 
  function anonymous(locals) {
jade.debug = [{ lineno: 1, filename: undefined }];
try {
var buf = [];
jade.indent = [];
jade.debug.unshift({ lineno: 1, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 1, filename: jade.debug[0].filename });
buf.push("\n<table style=\"border-top: 2px solid #000; border-bottom: 1px solid #ccc; padding: 4px 0; width: 100%; font-size: 11px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 3, filename: jade.debug[0].filename });
buf.push("\n  <tbody>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 4, filename: jade.debug[0].filename });
buf.push("\n    <tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 4, filename: jade.debug[0].filename });
buf.push("\n      <td style=\"width: 156px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 5, filename: jade.debug[0].filename });
buf.push("<a href=\"http://studybreakapp.com/\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 6, filename: jade.debug[0].filename });
buf.push("<img src=\"http://www.creativelicencedigital.com/images/signature/sb-feature-2012.png\" border=\"0\" alt=\"Download StudyBreak\" style=\"width: 150px; height: 76px; border: 0;\"/>");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.unshift({ lineno: 8, filename: jade.debug[0].filename });
buf.push("\n      <td>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 8, filename: jade.debug[0].filename });
buf.push("\n        <div style=\"margin: 0 0 2px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 9, filename: jade.debug[0].filename });
buf.push("<a href=\"http://studybreakapp.com/\" style=\"color: #000; font-size: 15px; text-decoration: none;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 10, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 10, filename: jade.debug[0].filename });
buf.push("StudyBreak");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 11, filename: jade.debug[0].filename });
buf.push("for iPhone");
jade.debug.shift();
jade.debug.unshift({ lineno: 12, filename: jade.debug[0].filename });
buf.push("<sup>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 12, filename: jade.debug[0].filename });
buf.push("&reg;");
jade.debug.shift();
jade.debug.shift();
buf.push("</sup>");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 13, filename: jade.debug[0].filename });
buf.push("\n        <div style=\"margin: 0 0 4px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 14, filename: jade.debug[0].filename });
buf.push("<a href=\"http://studybreakapp.com/\" style=\"color: #444; font-size: 11px; text-decoration: none;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 15, filename: jade.debug[0].filename });
buf.push("App Store Best of 2012 - iPhone");
jade.debug.shift();
jade.debug.unshift({ lineno: 16, filename: jade.debug[0].filename });
buf.push("<sup>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 16, filename: jade.debug[0].filename });
buf.push("&reg;");
jade.debug.shift();
jade.debug.shift();
buf.push("</sup>");
jade.debug.shift();
jade.debug.unshift({ lineno: 17, filename: jade.debug[0].filename });
buf.push("- Discover with Friends");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 18, filename: jade.debug[0].filename });
buf.push("\n        <div style=\"margin: 0;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 19, filename: jade.debug[0].filename });
buf.push("<a href=\"http://studybreakapp.com/\" style=\"color: #000; font-size: 13px; text-decoration: none;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 20, filename: jade.debug[0].filename });
buf.push("Discover how we helped students spend more time with their friends with our app StudyBreak");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n      </td>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n    </tr>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n  </tbody>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n</table>");
jade.debug.shift();
jade.debug.unshift({ lineno: 22, filename: jade.debug[0].filename });
buf.push("\n<div>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 22, filename: jade.debug[0].filename });
buf.push("<img src=\"http://www.creativelicencedigital.com/images/signature/awards.png\" alt=\"Award winning application development\" style=\"border: 0; max-width: 100%; width: 560px; height: 32px; background: #eee;\"/>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.shift();;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade.debug[0].filename, jade.debug[0].lineno);
}
};

Templates["shoppernova"] = 
  function anonymous(locals) {
jade.debug = [{ lineno: 1, filename: undefined }];
try {
var buf = [];
jade.indent = [];
jade.debug.unshift({ lineno: 1, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 2, filename: jade.debug[0].filename });
buf.push("\n<html>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 3, filename: jade.debug[0].filename });
buf.push("\n  <body>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 3, filename: jade.debug[0].filename });
buf.push("\n    <div style=\"color: #666; font-family: Helvetica,Arial,sans-serif; max-width: 500px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 4, filename: jade.debug[0].filename });
buf.push("\n      <table style=\"border-top: 3px solid #000; border-bottom: 3px solid #000; padding: 5px 0; font-size: 11px; width: 500px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 6, filename: jade.debug[0].filename });
buf.push("\n        <tbody>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 7, filename: jade.debug[0].filename });
buf.push("\n          <tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 7, filename: jade.debug[0].filename });
buf.push("\n            <td width=\"90\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 8, filename: jade.debug[0].filename });
buf.push("<img src=\"http://www.creativelicencedigital.com/images/signature/shoppernova_100x100.png\" border=\"0\" alt=\"ShopperNova\" width=\"80\" height=\"80\"/>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.unshift({ lineno: 10, filename: jade.debug[0].filename });
buf.push("\n            <td>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 10, filename: jade.debug[0].filename });
buf.push("\n              <div style=\"color: #000; font-size: 14px; margin: 4px 0;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 11, filename: jade.debug[0].filename });
buf.push("" + (jade.escape((jade.interp = locals.firstname) == null ? '' : jade.interp)) + " " + (jade.escape((jade.interp = locals.lastname) == null ? '' : jade.interp)) + "");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 12, filename: jade.debug[0].filename });
buf.push("\n              <div style=\"color: #000; font-size: 12px; margin: 2px 0;\">" + (jade.escape(null == (jade.interp = locals.role) ? "" : jade.interp)));
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 13, filename: jade.debug[0].filename });
buf.push("\n              <div style=\"margin: 1px 0;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 13, filename: jade.debug[0].filename });
buf.push("ShopperNova");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 14, filename: jade.debug[0].filename });
buf.push("\n              <div style=\"margin: 1px 0;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 15, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 15, filename: jade.debug[0].filename });
buf.push("work ");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 16, filename: jade.debug[0].filename });
buf.push("(02) 9564 9916 ");
jade.debug.shift();
jade.debug.unshift({ lineno: 17, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 17, filename: jade.debug[0].filename });
buf.push("mobile ");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 18, filename: jade.debug[0].filename });
buf.push(jade.escape(null == (jade.interp = locals.mobile) ? "" : jade.interp));
jade.debug.shift();
jade.debug.shift();
buf.push("\n              </div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 19, filename: jade.debug[0].filename });
buf.push("\n              <div style=\"font-size: 11px; margin: 1px 0;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 20, filename: jade.debug[0].filename });
buf.push("<a" + (jade.attrs({ 'style':("color: #333;"), 'href':("mailto:" + (locals.shoppernova_email) + ""), 'target':("_blank") }, {"style":true,"href":true,"target":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 21, filename: jade.debug[0].filename });
buf.push(jade.escape(null == (jade.interp = locals.shoppernova_email) ? "" : jade.interp));
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n            </td>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n          </tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 23, filename: jade.debug[0].filename });
buf.push("\n          <tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 23, filename: jade.debug[0].filename });
buf.push("\n            <td colspan=\"2\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 24, filename: jade.debug[0].filename });
buf.push("<a style=\"color: #000; font-size: 16px; font-weight: bold; text-decoration: none;\" href=\"http://bit.ly/ShopperNova\" target=\"_blank\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 25, filename: jade.debug[0].filename });
buf.push("Download ShopperNova now!");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n          </tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 28, filename: jade.debug[0].filename });
buf.push("\n          <tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 28, filename: jade.debug[0].filename });
buf.push("\n            <td colspan=\"2\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 29, filename: jade.debug[0].filename });
buf.push("\n              <p style=\"color: #999; font-size: 9px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
buf.push("\n                ");
jade.debug.unshift({ lineno: 30, filename: jade.debug[0].filename });
buf.push("This message may contain confidential or legally privileged information.");
jade.debug.shift();
buf.push("\n                ");
jade.debug.unshift({ lineno: 31, filename: jade.debug[0].filename });
buf.push("If you think it was sent to you by mistake, please delete all copies and");
jade.debug.shift();
buf.push("\n                ");
jade.debug.unshift({ lineno: 32, filename: jade.debug[0].filename });
buf.push("advise the sender. Please consider the environment before printing this");
jade.debug.shift();
buf.push("\n                ");
jade.debug.unshift({ lineno: 33, filename: jade.debug[0].filename });
buf.push("email.");
jade.debug.shift();
jade.debug.shift();
buf.push("\n              </p>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n            </td>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n          </tr>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n        </tbody>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n      </table>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n    </div>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n  </body>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n</html>");
jade.debug.shift();
jade.debug.shift();;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade.debug[0].filename, jade.debug[0].lineno);
}
};

Templates["signature"] = 
  function anonymous(locals) {
jade.debug = [{ lineno: 1, filename: undefined }];
try {
var buf = [];
var locals_ = (locals || {}),contact = locals_.contact;jade.indent = [];
jade.debug.unshift({ lineno: 1, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 1, filename: jade.debug[0].filename });
buf.push("<!DOCTYPE html>");
jade.debug.shift();
jade.debug.unshift({ lineno: 3, filename: jade.debug[0].filename });
buf.push("\n<html>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 3, filename: jade.debug[0].filename });
var font = "font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;"
jade.debug.shift();
jade.debug.unshift({ lineno: 4, filename: jade.debug[0].filename });
var bodyCopy = "color: #000; font-size: 11px; margin: 0 0 2px; font-style: normal;";
jade.debug.shift();
jade.debug.unshift({ lineno: 5, filename: jade.debug[0].filename });
var bodyCopyH1 = "color: #000; font-size: 15px; margin: 0 0 2px;";
jade.debug.shift();
jade.debug.unshift({ lineno: 6, filename: jade.debug[0].filename });
var bodyCopyH2 = "color: #000; font-size: 13px; margin: 0 0 2px;";
jade.debug.shift();
jade.debug.unshift({ lineno: 7, filename: jade.debug[0].filename });
var linkStyle = "text-decoration: none; color: #333;";
jade.debug.shift();
jade.debug.unshift({ lineno: 10, filename: jade.debug[0].filename });
buf.push("\n  <body>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 10, filename: jade.debug[0].filename });
buf.push("\n    <div" + (jade.attrs({ terse: true, 'style':(font + "color: #444; width: 450px; background: #fff;") }, {"style":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 11, filename: jade.debug[0].filename });
buf.push("\n      <style type=\"text/css\">");
jade.debug.unshift({ lineno: 12, filename: jade.debug[0].filename });
buf.push("\n        ");
jade.debug.unshift({ lineno: 12, filename: jade.debug[0].filename });
buf.push("div, p, a, li, td { ");
jade.debug.shift();
buf.push("\n        ");
jade.debug.unshift({ lineno: 13, filename: jade.debug[0].filename });
buf.push("  -webkit-text-size-adjust: none;");
jade.debug.shift();
buf.push("\n        ");
jade.debug.unshift({ lineno: 14, filename: jade.debug[0].filename });
buf.push("  line-height: 1.1em;");
jade.debug.shift();
buf.push("\n        ");
jade.debug.unshift({ lineno: 15, filename: jade.debug[0].filename });
buf.push("}");
jade.debug.shift();
buf.push("\n        ");
jade.debug.unshift({ lineno: 16, filename: jade.debug[0].filename });
buf.push("a[href^=tel]{");
jade.debug.shift();
buf.push("\n        ");
jade.debug.unshift({ lineno: 17, filename: jade.debug[0].filename });
buf.push("    color: inherit;");
jade.debug.shift();
buf.push("\n        ");
jade.debug.unshift({ lineno: 18, filename: jade.debug[0].filename });
buf.push("    text-decoration: none;");
jade.debug.shift();
buf.push("\n        ");
jade.debug.unshift({ lineno: 19, filename: jade.debug[0].filename });
buf.push("}");
jade.debug.shift();
buf.push("\n        ");
jade.debug.unshift({ lineno: 20, filename: jade.debug[0].filename });
buf.push("");
jade.debug.shift();
jade.debug.shift();
buf.push("\n      </style>");
jade.debug.shift();
jade.debug.unshift({ lineno: 21, filename: jade.debug[0].filename });
buf.push("\n      <table cellspacing=\"0\" cellpadding=\"0\" width=\"450\" style=\"padding: 4px 0; font-size: 11px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 23, filename: jade.debug[0].filename });
buf.push("\n        <tbody>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 24, filename: jade.debug[0].filename });
buf.push("\n          <tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 24, filename: jade.debug[0].filename });
buf.push("\n            <td style=\"width: 160px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 25, filename: jade.debug[0].filename });
buf.push("<a href=\"http://www.creativelicencedigital.com/\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 26, filename: jade.debug[0].filename });
buf.push("<img src=\"http://www.creativelicencedigital.com/images/signature/cld_150x90.png\" alt=\"Creative Licence Digital\" style=\"width: 150px; height: 90px; border: 0;\">");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.unshift({ lineno: 28, filename: jade.debug[0].filename });
buf.push("\n            <td>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 28, filename: jade.debug[0].filename });
buf.push("\n              <div" + (jade.attrs({ terse: true, 'style':(bodyCopyH1) }, {"style":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 29, filename: jade.debug[0].filename });
buf.push("" + (jade.escape((jade.interp = contact.firstname) == null ? '' : jade.interp)) + " " + (jade.escape((jade.interp = contact.lastname) == null ? '' : jade.interp)) + "");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 31, filename: jade.debug[0].filename });
if ( contact.role)
{
jade.debug.unshift({ lineno: 32, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 32, filename: jade.debug[0].filename });
buf.push("\n              <div" + (jade.attrs({ terse: true, 'style':(bodyCopyH2) }, {"style":true})) + ">" + (jade.escape(null == (jade.interp = contact.role) ? "" : jade.interp)));
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.shift();
}
jade.debug.shift();
jade.debug.unshift({ lineno: 34, filename: jade.debug[0].filename });
if ( contact.email)
{
jade.debug.unshift({ lineno: 35, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 35, filename: jade.debug[0].filename });
buf.push("\n              <div" + (jade.attrs({ terse: true, 'style':(bodyCopy) }, {"style":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 36, filename: jade.debug[0].filename });
buf.push("<a" + (jade.attrs({ terse: true, 'style':(linkStyle), 'href':("mailto:" + (contact.email) + "") }, {"style":true,"href":true})) + ">" + (jade.escape(null == (jade.interp = contact.email) ? "" : jade.interp)));
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.shift();
}
jade.debug.shift();
jade.debug.unshift({ lineno: 38, filename: jade.debug[0].filename });
buf.push("\n              <div" + (jade.attrs({ terse: true, 'style':(bodyCopy) }, {"style":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 39, filename: jade.debug[0].filename });
buf.push("<a" + (jade.attrs({ terse: true, 'style':(linkStyle), 'href':("http://www.creativelicencedigital.com/") }, {"style":true,"href":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 39, filename: jade.debug[0].filename });
buf.push("creativelicencedigital.com");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 41, filename: jade.debug[0].filename });
if ( contact.mobile)
{
jade.debug.unshift({ lineno: 42, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 42, filename: jade.debug[0].filename });
buf.push("\n              <div" + (jade.attrs({ terse: true, 'style':(bodyCopy) }, {"style":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 43, filename: jade.debug[0].filename });
buf.push("<a" + (jade.attrs({ terse: true, 'href':("tel:" + (contact.mobile) + ""), 'style':(linkStyle) }, {"href":true,"style":true})) + ">" + (jade.escape(null == (jade.interp = contact.mobile) ? "" : jade.interp)));
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.shift();
}
jade.debug.shift();
jade.debug.unshift({ lineno: 45, filename: jade.debug[0].filename });
buf.push("\n              <div" + (jade.attrs({ terse: true, 'style':(bodyCopy) }, {"style":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 46, filename: jade.debug[0].filename });
buf.push("<a" + (jade.attrs({ terse: true, 'style':(linkStyle), 'href':("http://twitter.com/Cre8iveLicence") }, {"style":true,"href":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 46, filename: jade.debug[0].filename });
buf.push("@Cre8iveLicence");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n            </td>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n          </tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 49, filename: jade.debug[0].filename });
buf.push("\n          <tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 49, filename: jade.debug[0].filename });
buf.push("\n            <td colspan=\"2\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 50, filename: jade.debug[0].filename });
buf.push("\n              <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" style=\"margin-top: 8px; border-top: 1px solid #ccc;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 52, filename: jade.debug[0].filename });
buf.push("\n                <tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 52, filename: jade.debug[0].filename });
buf.push("\n                  <td width=\"160px\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 53, filename: jade.debug[0].filename });
buf.push("\n                    <div style=\"font-weight: bold; color: #000; font-size: 12px; margin: 8px 0 2px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 53, filename: jade.debug[0].filename });
buf.push("Sydney Office");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 54, filename: jade.debug[0].filename });
buf.push("\n                    <div" + (jade.attrs({ terse: true, 'style':(bodyCopy) }, {"style":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 54, filename: jade.debug[0].filename });
buf.push("<a" + (jade.attrs({ terse: true, 'href':("http://maps.google.com/?q=Level 1 Park Lane Arcade, 13 The Corso Manly NSW 2095"), 'style':(linkStyle) }, {"href":true,"style":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 55, filename: jade.debug[0].filename });
buf.push("Level 1, Park Lane Arcade");
jade.debug.shift();
jade.debug.unshift({ lineno: 57, filename: jade.debug[0].filename });
buf.push("<br>");
jade.debug.shift();
jade.debug.unshift({ lineno: 57, filename: jade.debug[0].filename });
buf.push("13 The Corso");
jade.debug.shift();
jade.debug.unshift({ lineno: 59, filename: jade.debug[0].filename });
buf.push("<br>");
jade.debug.shift();
jade.debug.unshift({ lineno: 59, filename: jade.debug[0].filename });
buf.push("Manly NSW 2095");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 60, filename: jade.debug[0].filename });
buf.push("<a" + (jade.attrs({ terse: true, 'href':("tel:+61299772228"), 'style':(bodyCopy + linkStyle) }, {"href":true,"style":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 60, filename: jade.debug[0].filename });
buf.push("(02) 9977 2228");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n                  </td>");
jade.debug.shift();
jade.debug.unshift({ lineno: 63, filename: jade.debug[0].filename });
buf.push("\n                  <td>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 63, filename: jade.debug[0].filename });
buf.push("\n                    <div style=\"font-weight: bold; color: #000; font-size: 12px; margin: 8px 0 2px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 63, filename: jade.debug[0].filename });
buf.push("New York Office");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 64, filename: jade.debug[0].filename });
buf.push("\n                    <div" + (jade.attrs({ terse: true, 'style':(bodyCopy) }, {"style":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 64, filename: jade.debug[0].filename });
buf.push("<a" + (jade.attrs({ terse: true, 'href':("http://maps.google.com/?q=Level 11, 41 E 11th Street New York, NY 10003"), 'style':(linkStyle) }, {"href":true,"style":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 65, filename: jade.debug[0].filename });
buf.push("Level 11");
jade.debug.shift();
jade.debug.unshift({ lineno: 67, filename: jade.debug[0].filename });
buf.push("<br>");
jade.debug.shift();
jade.debug.unshift({ lineno: 67, filename: jade.debug[0].filename });
buf.push("41 E 11th Street");
jade.debug.shift();
jade.debug.unshift({ lineno: 69, filename: jade.debug[0].filename });
buf.push("<br>");
jade.debug.shift();
jade.debug.unshift({ lineno: 69, filename: jade.debug[0].filename });
buf.push("New York, NY 10003");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 70, filename: jade.debug[0].filename });
buf.push("<a" + (jade.attrs({ terse: true, 'href':("tel:+12123311100"), 'style':(bodyCopy + linkStyle) }, {"href":true,"style":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 70, filename: jade.debug[0].filename });
buf.push("212 331 1100");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n                  </td>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n                </tr>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n              </table>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n            </td>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n          </tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 74, filename: jade.debug[0].filename });
buf.push("\n          <tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 74, filename: jade.debug[0].filename });
buf.push("\n            <td id=\"awards\" colspan=\"2\" style=\"padding: 6px 0;\">" + (null == (jade.interp = locals.awards) ? "" : jade.interp));
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n          </tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 77, filename: jade.debug[0].filename });
buf.push("\n          <tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 77, filename: jade.debug[0].filename });
buf.push("\n            <td colspan=\"2\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 78, filename: jade.debug[0].filename });
buf.push("\n              <p style=\"color: #999; font-size: 9px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 79, filename: jade.debug[0].filename });
buf.push("This message may contain confidential or legally privileged information. If you think it was sent to you by mistake, please delete all copies and advise the sender. Please consider the environment before printing this email. Apple, the Apple logo, and iPhone are trademarks of Apple Inc., registered in the U.S. and other countries. App Store is a service mark of Apple Inc.");
jade.debug.shift();
jade.debug.shift();
buf.push("</p>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n            </td>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n          </tr>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n        </tbody>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n      </table>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n    </div>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n  </body>");
jade.debug.shift();
jade.debug.shift();
buf.push("\n</html>");
jade.debug.shift();
jade.debug.shift();;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade.debug[0].filename, jade.debug[0].lineno);
}
};

