var Templates = {}; 

Templates["awardsList"] = 
  function anonymous(locals) {
jade.debug = [{ lineno: 1, filename: undefined }];
try {
var buf = [];
jade.debug.unshift({ lineno: 1, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 1, filename: jade.debug[0].filename });
buf.push("<div style=\"color:rgb(102,102,102);border-top: 2px solid #000;margin:2px 0px;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 2, filename: jade.debug[0].filename });
buf.push("<table width=\"100%\" style=\"margin: 2px 0px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 4, filename: jade.debug[0].filename });
buf.push("<tbody>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 5, filename: jade.debug[0].filename });
buf.push("<tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 5, filename: jade.debug[0].filename });
buf.push("<td style=\"font-size: 12px; font-family: arial; background-color: #eee; padding-left: 10px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 6, filename: jade.debug[0].filename });
buf.push("<a href=\"http://www.shoppernova.com.au/\" style=\"text-decoration: none; color: #777;\" target=\"_blank\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 8, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 8, filename: jade.debug[0].filename });
buf.push("<span style=\"color: #000;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 8, filename: jade.debug[0].filename });
buf.push("2013 Winner");
jade.debug.shift();
jade.debug.shift();
buf.push("</span>");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 9, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 9, filename: jade.debug[0].filename });
buf.push(" Scrambled");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 10, filename: jade.debug[0].filename });
buf.push(" | Games |");
jade.debug.shift();
jade.debug.unshift({ lineno: 11, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 11, filename: jade.debug[0].filename });
buf.push(" Australian Mobile Awards");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 13, filename: jade.debug[0].filename });
buf.push("<tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 13, filename: jade.debug[0].filename });
buf.push("<td style=\"font-size: 12px; font-family: arial; background-color: #eee; padding-left: 10px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 14, filename: jade.debug[0].filename });
buf.push("<a href=\"http://www.studybreakapp.com/\" style=\"text-decoration: none; color: #777;\" target=\"_blank\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 16, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 16, filename: jade.debug[0].filename });
buf.push("<span style=\"color: #000;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 16, filename: jade.debug[0].filename });
buf.push("2012 Winner");
jade.debug.shift();
jade.debug.shift();
buf.push("</span>");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 17, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 17, filename: jade.debug[0].filename });
buf.push(" Study Break");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 18, filename: jade.debug[0].filename });
buf.push(" | Discover with Friends |");
jade.debug.shift();
jade.debug.unshift({ lineno: 19, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 19, filename: jade.debug[0].filename });
buf.push(" App Store Best of | iPhone®");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 21, filename: jade.debug[0].filename });
buf.push("<tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 21, filename: jade.debug[0].filename });
buf.push("<td style=\"font-size: 12px; font-family: arial; background-color: #eee; padding-left: 10px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 22, filename: jade.debug[0].filename });
buf.push("<a href=\"http://www.shoppernova.com.au/\" style=\"text-decoration: none; color: #777;\" target=\"_blank\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 24, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 24, filename: jade.debug[0].filename });
buf.push("<span style=\"color: #000;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 24, filename: jade.debug[0].filename });
buf.push("2012 Finalist");
jade.debug.shift();
jade.debug.shift();
buf.push("</span>");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 25, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 25, filename: jade.debug[0].filename });
buf.push(" ShopperNova");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 26, filename: jade.debug[0].filename });
buf.push(" | Retail &amp; Shopping |");
jade.debug.shift();
jade.debug.unshift({ lineno: 27, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 27, filename: jade.debug[0].filename });
buf.push(" Australian Mobile Awards");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 29, filename: jade.debug[0].filename });
buf.push("<tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 29, filename: jade.debug[0].filename });
buf.push("<td style=\"font-size: 12px; font-family: arial; background-color: #eee; padding-left: 10px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 30, filename: jade.debug[0].filename });
buf.push("<a href=\"http://www.creativelicencedigital.com/brookfield-multiplex.asp\" style=\"text-decoration: none; color: #777;\" target=\"_blank\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 32, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 32, filename: jade.debug[0].filename });
buf.push("<span style=\"color: #000;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 32, filename: jade.debug[0].filename });
buf.push("2012 Finalist");
jade.debug.shift();
jade.debug.shift();
buf.push("</span>");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 33, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 33, filename: jade.debug[0].filename });
buf.push(" Brookfield Multiplex");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 34, filename: jade.debug[0].filename });
buf.push(" | Sales Force |");
jade.debug.shift();
jade.debug.unshift({ lineno: 35, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 35, filename: jade.debug[0].filename });
buf.push(" Australian Mobile Awards");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 37, filename: jade.debug[0].filename });
buf.push("<tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 37, filename: jade.debug[0].filename });
buf.push("<td style=\"font-size: 12px; font-family: arial; background-color: #eee; padding-left: 10px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 38, filename: jade.debug[0].filename });
buf.push("<a href=\"http://www.fieldintouch.com/\" style=\"text-decoration: none; color: #777;\" target=\"_blank\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 40, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 40, filename: jade.debug[0].filename });
buf.push("<span style=\"color: #000;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 40, filename: jade.debug[0].filename });
buf.push("2012 Finalist");
jade.debug.shift();
jade.debug.shift();
buf.push("</span>");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 41, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 41, filename: jade.debug[0].filename });
buf.push(" Field InTouch");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 42, filename: jade.debug[0].filename });
buf.push(" | In Field Services |");
jade.debug.shift();
jade.debug.unshift({ lineno: 43, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 43, filename: jade.debug[0].filename });
buf.push(" Australian Mobile Awards");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 45, filename: jade.debug[0].filename });
buf.push("<tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 45, filename: jade.debug[0].filename });
buf.push("<td style=\"font-size: 12px; font-family: arial; background-color: #eee; padding-left: 10px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 46, filename: jade.debug[0].filename });
buf.push("<a href=\"http://www.shoppernova.com.au/\" style=\"text-decoration: none; color: #777;\" target=\"_blank\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 48, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 48, filename: jade.debug[0].filename });
buf.push("<span style=\"color: #000;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 48, filename: jade.debug[0].filename });
buf.push("2011 Finalist");
jade.debug.shift();
jade.debug.shift();
buf.push("</span>");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 49, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 49, filename: jade.debug[0].filename });
buf.push(" Quickerfeet");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 50, filename: jade.debug[0].filename });
buf.push(" | Innovation Award |");
jade.debug.shift();
jade.debug.unshift({ lineno: 51, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 51, filename: jade.debug[0].filename });
buf.push(" AIMIA Awards 2011");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 53, filename: jade.debug[0].filename });
buf.push("<tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 53, filename: jade.debug[0].filename });
buf.push("<td style=\"font-size: 12px; font-family: arial; background-color: #eee; padding-left: 10px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 54, filename: jade.debug[0].filename });
buf.push("<a href=\"https://itunes.apple.com/au/app/woven-image/id407919710?mt=8\" style=\"text-decoration: none; color: #777;\" target=\"_blank\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 56, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 56, filename: jade.debug[0].filename });
buf.push("<span style=\"color: #000;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 56, filename: jade.debug[0].filename });
buf.push("2011 Winner");
jade.debug.shift();
jade.debug.shift();
buf.push("</span>");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 57, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 57, filename: jade.debug[0].filename });
buf.push(" Woven Image");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 58, filename: jade.debug[0].filename });
buf.push(" | Best B2B | In Field Services |");
jade.debug.shift();
jade.debug.unshift({ lineno: 59, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 59, filename: jade.debug[0].filename });
buf.push(" Australian Mobile Awards");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 61, filename: jade.debug[0].filename });
buf.push("<tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 61, filename: jade.debug[0].filename });
buf.push("<td style=\"font-size: 12px; font-family: arial; background-color: #eee; padding-left: 10px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 62, filename: jade.debug[0].filename });
buf.push("<a href=\"https://itunes.apple.com/au/app/whiskas-earster-cats/id431829440?mt=8\" style=\"text-decoration: none; color: #777;\" target=\"_blank\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 64, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 64, filename: jade.debug[0].filename });
buf.push("<span style=\"color: #000;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 64, filename: jade.debug[0].filename });
buf.push("2011 Winner");
jade.debug.shift();
jade.debug.shift();
buf.push("</span>");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 65, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 65, filename: jade.debug[0].filename });
buf.push(" Whiskas Earster Cats");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 66, filename: jade.debug[0].filename });
buf.push(" | Best Use of Advertising |");
jade.debug.shift();
jade.debug.unshift({ lineno: 67, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 67, filename: jade.debug[0].filename });
buf.push(" Australian Mobile Awards");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 69, filename: jade.debug[0].filename });
buf.push("<tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 69, filename: jade.debug[0].filename });
buf.push("<td style=\"font-size: 12px; font-family: arial; background-color: #eee; padding-left: 10px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 70, filename: jade.debug[0].filename });
buf.push("<a href=\"https://itunes.apple.com/au/app/woven-image/id407919710?mt=8\" style=\"text-decoration: none; color: #777;\" target=\"_blank\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 72, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 72, filename: jade.debug[0].filename });
buf.push("<span style=\"color: #000;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 72, filename: jade.debug[0].filename });
buf.push("2011 Winner");
jade.debug.shift();
jade.debug.shift();
buf.push("</span>");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 73, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 73, filename: jade.debug[0].filename });
buf.push(" Woven Image");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 74, filename: jade.debug[0].filename });
buf.push(" | Best App By Platform | iOS |");
jade.debug.shift();
jade.debug.unshift({ lineno: 75, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 75, filename: jade.debug[0].filename });
buf.push(" Australian Mobile Awards");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 77, filename: jade.debug[0].filename });
buf.push("<tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 77, filename: jade.debug[0].filename });
buf.push("<td style=\"font-size: 12px; font-family: arial; background-color: #eee; padding-left: 10px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 78, filename: jade.debug[0].filename });
buf.push("<a href=\"https://itunes.apple.com/au/app/medicines-list/id440111671?mt=8\" style=\"text-decoration: none; color: #777;\" target=\"_blank\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 80, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 80, filename: jade.debug[0].filename });
buf.push("<span style=\"color: #000;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 80, filename: jade.debug[0].filename });
buf.push("2011 Winner");
jade.debug.shift();
jade.debug.shift();
buf.push("</span>");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 81, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 81, filename: jade.debug[0].filename });
buf.push(" NPS Medicine Wise");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 82, filename: jade.debug[0].filename });
buf.push(" | Best Health App |");
jade.debug.shift();
jade.debug.unshift({ lineno: 83, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 83, filename: jade.debug[0].filename });
buf.push(" Australian Mobile Awards");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 85, filename: jade.debug[0].filename });
buf.push("<tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 85, filename: jade.debug[0].filename });
buf.push("<td style=\"font-size: 12px; font-family: arial; background-color: #eee; padding-left: 10px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 86, filename: jade.debug[0].filename });
buf.push("<a href=\"http://www.stgeorge.com.au/\" style=\"text-decoration: none; color: #777;\" target=\"_blank\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 88, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 88, filename: jade.debug[0].filename });
buf.push("<span style=\"color: #000;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 88, filename: jade.debug[0].filename });
buf.push("2011 Finalist");
jade.debug.shift();
jade.debug.shift();
buf.push("</span>");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 89, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 89, filename: jade.debug[0].filename });
buf.push(" St George Mobile Banking");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 90, filename: jade.debug[0].filename });
buf.push(" | Best Financial App |");
jade.debug.shift();
jade.debug.unshift({ lineno: 91, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 91, filename: jade.debug[0].filename });
buf.push(" Australian Mobile Awards");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 93, filename: jade.debug[0].filename });
buf.push("<tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 93, filename: jade.debug[0].filename });
buf.push("<td style=\"font-size: 12px; font-family: arial; background-color: #eee; padding-left: 10px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 94, filename: jade.debug[0].filename });
buf.push("<a href=\"https://itunes.apple.com/au/app/amnesty-burma/id397911134?mt=8\" style=\"text-decoration: none; color: #777;\" target=\"_blank\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 96, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 96, filename: jade.debug[0].filename });
buf.push("<span style=\"color: #000;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 96, filename: jade.debug[0].filename });
buf.push("2010 Finalist");
jade.debug.shift();
jade.debug.shift();
buf.push("</span>");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 97, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 97, filename: jade.debug[0].filename });
buf.push(" Amnesty International");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 98, filename: jade.debug[0].filename });
buf.push(" | Best Not for Profit App |");
jade.debug.shift();
jade.debug.unshift({ lineno: 99, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 99, filename: jade.debug[0].filename });
buf.push(" AIMIA Awards 2010");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tr>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tbody>");
jade.debug.shift();
jade.debug.shift();
buf.push("</table>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.shift();;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade.debug[0].filename, jade.debug[0].lineno);
}
};

Templates["awardsSimple"] = 
  function anonymous(locals) {
jade.debug = [{ lineno: 1, filename: undefined }];
try {
var buf = [];
jade.debug.unshift({ lineno: 1, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 1, filename: jade.debug[0].filename });
buf.push("<table style=\"border-top: 2px solid #000; border-bottom: 1px solid #ccc; padding: 4px 0; width: 100%; font-size: 11px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 3, filename: jade.debug[0].filename });
buf.push("<tbody>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 4, filename: jade.debug[0].filename });
buf.push("<tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 4, filename: jade.debug[0].filename });
buf.push("<td style=\"width: 156px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 5, filename: jade.debug[0].filename });
buf.push("<a href=\"http://studybreakapp.com/\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 6, filename: jade.debug[0].filename });
buf.push("<img src=\"http://www.creativelicencedigital.com/images/signature/sb-feature-2012.png\" border=\"0\" alt=\"Download StudyBreak\" style=\"width: 150px; height: 76px; border: 0;\"/>");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.unshift({ lineno: 8, filename: jade.debug[0].filename });
buf.push("<td>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 8, filename: jade.debug[0].filename });
buf.push("<div style=\"margin: 0 0 2px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 9, filename: jade.debug[0].filename });
buf.push("<a href=\"http://studybreakapp.com/\" style=\"color: #000; font-size: 15px; text-decoration: none;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 10, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 10, filename: jade.debug[0].filename });
buf.push("StudyBreak");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 11, filename: jade.debug[0].filename });
buf.push("for iPhone");
jade.debug.shift();
jade.debug.unshift({ lineno: 12, filename: jade.debug[0].filename });
buf.push("<sup>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 12, filename: jade.debug[0].filename });
buf.push("&reg;");
jade.debug.shift();
jade.debug.shift();
buf.push("</sup>");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 13, filename: jade.debug[0].filename });
buf.push("<div style=\"margin: 0 0 4px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 14, filename: jade.debug[0].filename });
buf.push("<a href=\"http://studybreakapp.com/\" style=\"color: #444; font-size: 11px; text-decoration: none;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 15, filename: jade.debug[0].filename });
buf.push("App Store Best of 2012 - iPhone");
jade.debug.shift();
jade.debug.unshift({ lineno: 16, filename: jade.debug[0].filename });
buf.push("<sup>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 16, filename: jade.debug[0].filename });
buf.push("&reg;");
jade.debug.shift();
jade.debug.shift();
buf.push("</sup>");
jade.debug.shift();
jade.debug.unshift({ lineno: 17, filename: jade.debug[0].filename });
buf.push("- Discover with Friends");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 18, filename: jade.debug[0].filename });
buf.push("<div style=\"margin: 0;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 19, filename: jade.debug[0].filename });
buf.push("<a href=\"http://studybreakapp.com/\" style=\"color: #000; font-size: 13px; text-decoration: none;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 20, filename: jade.debug[0].filename });
buf.push("Discover how we helped students spend more time with their friends with our app StudyBreak");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tr>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tbody>");
jade.debug.shift();
jade.debug.shift();
buf.push("</table>");
jade.debug.shift();
jade.debug.unshift({ lineno: 22, filename: jade.debug[0].filename });
buf.push("<div>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 22, filename: jade.debug[0].filename });
buf.push("<img src=\"http://www.creativelicencedigital.com/images/signature/awards.png\" alt=\"Award winning application development\" style=\"border: 0; max-width: 100%; width: 560px; height: 32px; background: #eee;\"/>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.shift();;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade.debug[0].filename, jade.debug[0].lineno);
}
};

Templates["shoppernova"] = 
  function anonymous(locals) {
jade.debug = [{ lineno: 1, filename: undefined }];
try {
var buf = [];
jade.debug.unshift({ lineno: 1, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 2, filename: jade.debug[0].filename });
buf.push("<html>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 3, filename: jade.debug[0].filename });
buf.push("<body>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 3, filename: jade.debug[0].filename });
buf.push("<div style=\"color: #666; font-family: Helvetica,Arial,sans-serif; max-width: 500px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 4, filename: jade.debug[0].filename });
buf.push("<table style=\"border-top: 3px solid #000; border-bottom: 3px solid #000; padding: 5px 0; font-size: 11px; width: 500px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 6, filename: jade.debug[0].filename });
buf.push("<tbody>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 7, filename: jade.debug[0].filename });
buf.push("<tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 7, filename: jade.debug[0].filename });
buf.push("<td width=\"90\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 8, filename: jade.debug[0].filename });
buf.push("<img src=\"http://www.creativelicencedigital.com/images/signature/shoppernova_100x100.png\" border=\"0\" alt=\"ShopperNova\" width=\"80\" height=\"80\"/>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.unshift({ lineno: 10, filename: jade.debug[0].filename });
buf.push("<td>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 10, filename: jade.debug[0].filename });
buf.push("<div style=\"color: #000; font-size: 14px; margin: 4px 0;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 11, filename: jade.debug[0].filename });
buf.push("" + (jade.escape((jade.interp = locals.firstname) == null ? '' : jade.interp)) + " " + (jade.escape((jade.interp = locals.lastname) == null ? '' : jade.interp)) + "");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 12, filename: jade.debug[0].filename });
buf.push("<div style=\"color: #000; font-size: 12px; margin: 2px 0;\">" + (jade.escape(null == (jade.interp = locals.role) ? "" : jade.interp)));
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 13, filename: jade.debug[0].filename });
buf.push("<div style=\"margin: 1px 0;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 13, filename: jade.debug[0].filename });
buf.push("ShopperNova");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 14, filename: jade.debug[0].filename });
buf.push("<div style=\"margin: 1px 0;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 15, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 15, filename: jade.debug[0].filename });
buf.push("work ");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 16, filename: jade.debug[0].filename });
buf.push("(02) 9564 9916 ");
jade.debug.shift();
jade.debug.unshift({ lineno: 17, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 17, filename: jade.debug[0].filename });
buf.push("mobile ");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 18, filename: jade.debug[0].filename });
buf.push(jade.escape(null == (jade.interp = locals.mobile) ? "" : jade.interp));
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 19, filename: jade.debug[0].filename });
buf.push("<div style=\"font-size: 11px; margin: 1px 0;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 20, filename: jade.debug[0].filename });
buf.push("<a" + (jade.attrs({ 'style':("color: #333;"), 'href':("mailto:" + (locals.shoppernova_email) + ""), 'target':("_blank") }, {"style":true,"href":true,"target":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 21, filename: jade.debug[0].filename });
buf.push(jade.escape(null == (jade.interp = locals.shoppernova_email) ? "" : jade.interp));
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 23, filename: jade.debug[0].filename });
buf.push("<tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 23, filename: jade.debug[0].filename });
buf.push("<td colspan=\"2\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 24, filename: jade.debug[0].filename });
buf.push("<a style=\"color: #000; font-size: 16px; font-weight: bold; text-decoration: none;\" href=\"http://bit.ly/ShopperNova\" target=\"_blank\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 25, filename: jade.debug[0].filename });
buf.push("Download ShopperNova now!");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 28, filename: jade.debug[0].filename });
buf.push("<tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 28, filename: jade.debug[0].filename });
buf.push("<td colspan=\"2\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 29, filename: jade.debug[0].filename });
buf.push("<p style=\"color: #999; font-size: 9px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 30, filename: jade.debug[0].filename });
buf.push("This message may contain confidential or legally privileged information.");
jade.debug.shift();
buf.push("\n");
jade.debug.unshift({ lineno: 31, filename: jade.debug[0].filename });
buf.push("If you think it was sent to you by mistake, please delete all copies and");
jade.debug.shift();
buf.push("\n");
jade.debug.unshift({ lineno: 32, filename: jade.debug[0].filename });
buf.push("advise the sender. Please consider the environment before printing this");
jade.debug.shift();
buf.push("\n");
jade.debug.unshift({ lineno: 33, filename: jade.debug[0].filename });
buf.push("email.");
jade.debug.shift();
jade.debug.shift();
buf.push("</p>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tr>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tbody>");
jade.debug.shift();
jade.debug.shift();
buf.push("</table>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.shift();
buf.push("</body>");
jade.debug.shift();
jade.debug.shift();
buf.push("</html>");
jade.debug.shift();
jade.debug.shift();;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade.debug[0].filename, jade.debug[0].lineno);
}
};

Templates["signature"] = 
  function anonymous(locals) {
jade.debug = [{ lineno: 1, filename: undefined }];
try {
var buf = [];
jade.debug.unshift({ lineno: 1, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 1, filename: jade.debug[0].filename });
buf.push("<!DOCTYPE html>");
jade.debug.shift();
jade.debug.unshift({ lineno: 3, filename: jade.debug[0].filename });
buf.push("<html>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 4, filename: jade.debug[0].filename });
buf.push("<body>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 4, filename: jade.debug[0].filename });
buf.push("<div style=\"color: #444; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; max-width: 560px; background: #fff; -webkit-text-size-adjust: none;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 5, filename: jade.debug[0].filename });
buf.push("<table style=\"border-top: 2px solid #000; padding: 4px 0; width: 560px; font-size: 11px; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 7, filename: jade.debug[0].filename });
buf.push("<tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 7, filename: jade.debug[0].filename });
buf.push("<td style=\"width: 156px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 8, filename: jade.debug[0].filename });
buf.push("<a href=\"http://www.creativelicencedigital.com/\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 9, filename: jade.debug[0].filename });
buf.push("<img src=\"http://www.creativelicencedigital.com/images/signature/cld_150x90.png\" alt=\"Creative Licence Digital\" style=\"width: 150px; height: 90px; border: 0;\">");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.unshift({ lineno: 11, filename: jade.debug[0].filename });
buf.push("<td>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 11, filename: jade.debug[0].filename });
buf.push("<div style=\"color: #000; font-size: 14px; margin: 2px 0;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 12, filename: jade.debug[0].filename });
buf.push("" + (jade.escape((jade.interp = locals.firstname) == null ? '' : jade.interp)) + " " + (jade.escape((jade.interp = locals.lastname) == null ? '' : jade.interp)) + "");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 14, filename: jade.debug[0].filename });
if ( locals.role)
{
jade.debug.unshift({ lineno: 15, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 15, filename: jade.debug[0].filename });
buf.push("<div style=\"color: #000; font-size: 12px; margin: 2px 0;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 16, filename: jade.debug[0].filename });
buf.push(jade.escape(null == (jade.interp = locals.role) ? "" : jade.interp));
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.shift();
}
jade.debug.shift();
jade.debug.unshift({ lineno: 18, filename: jade.debug[0].filename });
buf.push("<div style=\"color: #444; font-size: 11px; margin: 2px 0;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 19, filename: jade.debug[0].filename });
buf.push("Creative Licence Digital");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 21, filename: jade.debug[0].filename });
buf.push("<div style=\"color: #444; font-size: 11px; margin: 2px 0;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 22, filename: jade.debug[0].filename });
buf.push("Level 1, Park Lane Arcade, 13 The Corso, Manly NSW 2095");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 24, filename: jade.debug[0].filename });
buf.push("<div style=\"color: #444; font-size: 11px; margin: 2px 0;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 25, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 25, filename: jade.debug[0].filename });
buf.push("work ");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 26, filename: jade.debug[0].filename });
buf.push("(02) 9977 2228 ");
jade.debug.shift();
jade.debug.unshift({ lineno: 27, filename: jade.debug[0].filename });
if ( locals.mobile)
{
jade.debug.unshift({ lineno: 28, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 28, filename: jade.debug[0].filename });
buf.push("<strong>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 28, filename: jade.debug[0].filename });
buf.push("mobile ");
jade.debug.shift();
jade.debug.shift();
buf.push("</strong>");
jade.debug.shift();
jade.debug.unshift({ lineno: 29, filename: jade.debug[0].filename });
buf.push(jade.escape(null == (jade.interp = locals.mobile) ? "" : jade.interp));
jade.debug.shift();
jade.debug.shift();
}
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.unshift({ lineno: 31, filename: jade.debug[0].filename });
buf.push("<div style=\"font-size: 11px; margin: 2px 0;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 33, filename: jade.debug[0].filename });
buf.push("<a style=\"margin-right: 2px; text-decoration: none;\" href=\"http://twitter.com/Cre8iveLicence\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 35, filename: jade.debug[0].filename });
buf.push("<img src=\"http://www.creativelicencedigital.com/images/signature/twitter.png\" alt=\"Cre8ive Licence\" style=\"vertical-align: middle; border: 0; width: 15px; height: 15px\">");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.unshift({ lineno: 37, filename: jade.debug[0].filename });
if ( locals.email)
{
jade.debug.unshift({ lineno: 38, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 38, filename: jade.debug[0].filename });
buf.push("<a" + (jade.attrs({ terse: true, 'style':("color: #333;"), 'href':("mailto:" + (locals.email) + "") }, {"style":true,"href":true})) + ">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 39, filename: jade.debug[0].filename });
buf.push(jade.escape(null == (jade.interp = locals.email) ? "" : jade.interp));
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.unshift({ lineno: 40, filename: jade.debug[0].filename });
buf.push(" | ");
jade.debug.shift();
jade.debug.shift();
}
jade.debug.shift();
jade.debug.unshift({ lineno: 42, filename: jade.debug[0].filename });
buf.push("<a style=\"color: #333;\" href=\"http://www.creativelicencedigital.com/\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 42, filename: jade.debug[0].filename });
buf.push("creativelicencedigital.com");
jade.debug.shift();
jade.debug.shift();
buf.push("</a>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 45, filename: jade.debug[0].filename });
buf.push("<tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 45, filename: jade.debug[0].filename });
buf.push("<td colspan=\"2\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 46, filename: jade.debug[0].filename });
buf.push("<div id=\"awards\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tr>");
jade.debug.shift();
jade.debug.unshift({ lineno: 49, filename: jade.debug[0].filename });
buf.push("<tr>");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 49, filename: jade.debug[0].filename });
buf.push("<td colspan=\"2\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 50, filename: jade.debug[0].filename });
buf.push("<p style=\"color: #999; font-size: 9px;\">");
jade.debug.unshift({ lineno: undefined, filename: jade.debug[0].filename });
jade.debug.unshift({ lineno: 51, filename: jade.debug[0].filename });
buf.push("This message may contain confidential or legally privileged information. If you think it was sent to you by mistake, please delete all copies and advise the sender. Please consider the environment before printing this email. Apple, the Apple logo, and iPhone are trademarks of Apple Inc., registered in the U.S. and other countries. App Store is a service mark of Apple Inc.");
jade.debug.shift();
jade.debug.shift();
buf.push("</p>");
jade.debug.shift();
jade.debug.shift();
buf.push("</td>");
jade.debug.shift();
jade.debug.shift();
buf.push("</tr>");
jade.debug.shift();
jade.debug.shift();
buf.push("</table>");
jade.debug.shift();
jade.debug.shift();
buf.push("</div>");
jade.debug.shift();
jade.debug.shift();
buf.push("</body>");
jade.debug.shift();
jade.debug.shift();
buf.push("</html>");
jade.debug.shift();
jade.debug.shift();;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade.debug[0].filename, jade.debug[0].lineno);
}
};

